apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: pipe-one-pub
description: sample pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: []
 - targetId: qsprod
   profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/my-project1/locations/asia-east1-a/clusters/sanket-public-cluster
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: production cluster
gke:
 cluster: projects/my-project1/locations/asia-east1-a/clusters/test-production-cluster



